language: python

python:
  - "2.6"
  - "2.7"

install:
  - pip install numpy
  - pip install nose
  - pip install mpi4py
  - pip install multiprocessing
  - pip install scipy
  - pip install sklearn

script:
  - nosetests  astroabc_mpi/tests.py

